source 'https://rubygems.org'

gem 'rails', '3.2.7'
gem 'sqlite3'
gem 'thin'
gem 'jquery-rails'

gem 'devise'
gem 'cancan'
gem 'friendly_id'
gem 'paperclip'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem 'wirb'
  gem 'debugger'
  gem 'quiet_assets'
end

group :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner'
  gem 'minitest'
  gem 'turn'
end

