source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3'
gem 'thin'
gem 'jquery-rails'

gem 'devise'
gem 'cancan'
gem 'friendly_id'
gem 'paperclip'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem 'quiet_assets'
  gem 'rails-footnotes'
end

group :test do
  gem 'minitest'
  gem 'turn'
end

